### ISSUE TITLE
No se debe usar la clase DB directamente desdel el contralador 

### ISSUE THREAD

**Issue by Ivanca** [NiKoT1Na/valarabel#1]
En ProdController.php no se debe usar la clase DB si no acceder a la informacion a travez del modelo (Prod.php) como usualmente se hace en laravel. XD

**Comment by NiKoT1Na** [comment]
.l.

**Comment by NiKoT1Na** [comment]
double .l.

**Comment by NiKoT1Na** [comment]
ya esta solucionado
